

services:
  app:
    build: .
    ports:
      - "8081:8080"

    command: bash -c "alembic upgrade head"
    
    depends_on:
      - db
    environment:
      - POSTGRES_USER=darix
      - POSTGRES_PASSWORD=darix
      - POSTGRES_DB=darix
      - POSTGRES_SERVER=db
      - PYTHONPATH=/app

  db:
    image: postgres:12.4
    
    ports:

      - "8001:5432"
    
    environment:
      - POSTGRES_USER=darix
      - POSTGRES_PASSWORD=darix
      - POSTGRES_DB=darix
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U darix"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
